### ISSUE TITLE
Discuss Font Size Standard

### ISSUE THREAD

**Issue by Panchicd** [comparaonline/design-style-guide#4]
Pixels, em or percentages?

Google Recommendations:

> Use 16px as the base font-size, adjust the rest using percentages. (For responsive design)

https://developers.google.com/speed/docs/insights/UseLegibleFontSizes
https://varvy.com/mobile/legible-font-size.html

https://www.futurehosting.com/blog/web-design-basics-rem-vs-em-vs-px-sizing-elements-in-css/
https://css-tricks.com/rems-ems/

**Comment by feliguez** [comment]
I used to set 16px as the base font-size on body tag even the default was that. Because, on that way I can be sure on all browsers. Then on every new font-size I used with em. Unfortunately Hector don't trust me (kidding)
I suggest set the base to 16px on body tag and slowly change the rest.

**Comment by hectorpalmatellez** [comment]
> I suggest set the base to 16px on body tag and slowly change the rest.

Agree :point_up:

**Comment by hectorpalmatellez** [comment]
#9 Using Ems

**Comment by feliguez** [comment]
Great!

Should we close this issue?

**Comment by hectorpalmatellez** [comment]
Closing.
